### ISSUE TITLE
Reflection usage in FileMapUtil incompatible with module reflection restrictions

### ISSUE THREAD

**Issue by Col-E** [Col-E/LL-Java-Zip#9]
Reflection usage in  84e953b9db2f2b5d36a33e978f5f267f8d4d4aa7 does not work in locked down environments _(Such as Java 16+)_

```
java.lang.reflect.InaccessibleObjectException: Unable to make private native long sun.nio.ch.FileChannelImpl.map0(int,long,long,boolean) throws java.io.IOException accessible: module java.base does not "opens sun.nio.ch" to unnamed module @23223dd8
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at software.coley.llzip.util.FileMapUtil.<clinit>(FileMapUtil.java:66)
```

**Comment by Col-E** [comment]
Huh, seems to be working now as of Java 16-18.

Will open if this comes up again later.
